from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = []

if not GetDepend('IDF_LWIP'):
    group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
