# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs = objs + SConscript('SConscript_idf')
objs = objs + SConscript('SConscript_libs')
# objs = objs + SConscript('SConscript_lwip')
objs = objs + SConscript('SConscript_mbedtls')

Return('objs')
